import crypto from "node:crypto";

export type GitHubAppConfig = {
  appId: string;
  privateKey: string;
  webhookSecret: string;
};

export type GitHubRepository = {
  id: number;
  fullName: string;
  defaultBranch: string;
  private: boolean;
  htmlUrl: string;
};

export type GitHubFinding = {
  title: string;
  detail: string;
  severity: "critical" | "high" | "medium" | "low";
  scanId: string;
};

export type GitHubRequest = (
  path: string,
  init?: RequestInit,
) => Promise<Response>;

function base64Url(value: string | Buffer): string {
  return Buffer.from(value)
    .toString("base64")
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");
}

export function readGitHubAppConfig(
  env: Record<string, string | undefined> = process.env,
): GitHubAppConfig | null {
  const appId = env.GITHUB_APP_ID?.trim();
  const privateKey = env.GITHUB_APP_PRIVATE_KEY?.replace(/\\n/g, "\n").trim();
  const webhookSecret = env.GITHUB_WEBHOOK_SECRET?.trim();
  if (!appId || !privateKey || !webhookSecret) return null;
  return { appId, privateKey, webhookSecret };
}

export function createGitHubAppJwt(
  config: Pick<GitHubAppConfig, "appId" | "privateKey">,
  nowSeconds = Math.floor(Date.now() / 1000),
): string {
  const header = base64Url(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const payload = base64Url(
    JSON.stringify({
      iat: nowSeconds - 60,
      exp: nowSeconds + 9 * 60,
      iss: config.appId,
    }),
  );
  const unsigned = `${header}.${payload}`;
  const signature = crypto.sign("RSA-SHA256", Buffer.from(unsigned), {
    key: config.privateKey,
  });
  return `${unsigned}.${base64Url(signature)}`;
}

export function createGitHubRequest(token: string): GitHubRequest {
  return (path, init = {}) =>
    fetch(`https://api.github.com${path}`, {
      ...init,
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${token}`,
        "X-GitHub-Api-Version": "2022-11-28",
        ...init.headers,
      },
    });
}

async function readJson<T>(response: Response): Promise<T> {
  if (!response.ok) {
    const message = await response.text();
    throw new Error(
      `GitHub API ${response.status}: ${message || response.statusText}`,
    );
  }
  return (await response.json()) as T;
}

export async function createInstallationToken(
  installationId: string,
  appRequest: GitHubRequest,
): Promise<string> {
  const response = await appRequest(
    `/app/installations/${installationId}/access_tokens`,
    {
      method: "POST",
    },
  );
  const result = await readJson<{ token: string }>(response);
  return result.token;
}

export function parseRepositoryName(repository: string): {
  owner: string;
  repo: string;
} {
  const match = repository
    .trim()
    .match(/^([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)$/);
  if (!match)
    throw new Error("Repository must use the owner/repository format");
  return { owner: match[1], repo: match[2] };
}

export async function connectGitHubRepository(
  repository: string,
  request: GitHubRequest,
): Promise<GitHubRepository> {
  const { owner, repo } = parseRepositoryName(repository);
  const response = await request(`/repos/${owner}/${repo}`);
  const data = await readJson<{
    id: number;
    full_name: string;
    default_branch: string;
    private: boolean;
    html_url: string;
  }>(response);
  return {
    id: data.id,
    fullName: data.full_name,
    defaultBranch: data.default_branch,
    private: data.private,
    htmlUrl: data.html_url,
  };
}

export function buildFindingIssue(
  finding: GitHubFinding,
  scanUrl: string,
): { title: string; body: string; labels: string[] } {
  return {
    title: `[Launch Check] ${finding.title}`,
    body: [
      "## Launch Check finding",
      "",
      finding.detail,
      "",
      `- Severity: **${finding.severity}**`,
      `- Scan: [${finding.scanId}](${scanUrl})`,
      "",
      "Generated by Launch Check.",
    ].join("\n"),
    labels: ["launch-check", `severity:${finding.severity}`],
  };
}

export async function createFindingIssue(
  repository: string,
  finding: GitHubFinding,
  scanUrl: string,
  request: GitHubRequest,
): Promise<{ number: number; htmlUrl: string }> {
  const { owner, repo } = parseRepositoryName(repository);
  const response = await request(`/repos/${owner}/${repo}/issues`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(buildFindingIssue(finding, scanUrl)),
  });
  const data = await readJson<{ number: number; html_url: string }>(response);
  return { number: data.number, htmlUrl: data.html_url };
}

export async function linkScanToCommit(
  repository: string,
  sha: string,
  scanId: string,
  scanUrl: string,
  request: GitHubRequest,
): Promise<{ id: number; htmlUrl: string }> {
  const { owner, repo } = parseRepositoryName(repository);
  if (!/^[a-f0-9]{7,40}$/i.test(sha)) throw new Error("Invalid commit SHA");
  const response = await request(`/repos/${owner}/${repo}/statuses/${sha}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      state: "pending",
      target_url: scanUrl,
      description: `Launch Check scan ${scanId}`.slice(0, 140),
      context: "launch-check/scan",
    }),
  });
  const data = await readJson<{ id: number; url: string }>(response);
  return { id: data.id, htmlUrl: data.url };
}

export async function publishPullRequestCheck(
  repository: string,
  sha: string,
  input: {
    scanId: string;
    scanUrl: string;
    score: number;
    summary: string;
  },
  request: GitHubRequest,
): Promise<{ id: number; htmlUrl: string }> {
  const { owner, repo } = parseRepositoryName(repository);
  const conclusion = input.score >= 70 ? "success" : "failure";
  const response = await request(`/repos/${owner}/${repo}/check-runs`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: "Launch Check",
      head_sha: sha,
      status: "completed",
      conclusion,
      details_url: input.scanUrl,
      external_id: input.scanId,
      output: {
        title: `Launch score: ${input.score}`,
        summary: input.summary,
      },
    }),
  });
  const data = await readJson<{ id: number; html_url: string }>(response);
  return { id: data.id, htmlUrl: data.html_url };
}

export function verifyGitHubWebhook(
  payload: string,
  signature: string | null,
  secret: string,
): boolean {
  if (!signature?.startsWith("sha256=") || !secret) return false;
  const expected = `sha256=${crypto.createHmac("sha256", secret).update(payload).digest("hex")}`;
  const actualBuffer = Buffer.from(signature);
  const expectedBuffer = Buffer.from(expected);
  return (
    actualBuffer.length === expectedBuffer.length &&
    crypto.timingSafeEqual(actualBuffer, expectedBuffer)
  );
}

export function handleGitHubWebhook(
  event: string | null,
  deliveryId: string | null,
  payload: unknown,
): { accepted: true; event: string; deliveryId: string; action?: string } {
  if (!event || !deliveryId) throw new Error("Missing GitHub webhook headers");
  const action =
    typeof payload === "object" && payload && "action" in payload
      ? String((payload as { action?: unknown }).action ?? "") || undefined
      : undefined;
  return { accepted: true, event, deliveryId, action };
}
